  - platform: spotify
    client_id: !secret spotify_id
    client_secret: !secret spotify_secret
    
  - platform: webostv
    host: !secret webostv_ip
    name: Living Room TV
    turn_on_action:
        service: wake_on_lan.send_magic_packet
        data:
            mac: $secret webostv_mac
            
  - platform: roku
    host: !secret roku_ip