#----------------------------------------------------
# Home to Office
# The time it takes Scott to commute. Used to change
# light color in bedroom.
#----------------------------------------------------
  - platform: waze_travel_time
    origin: !secret address_home
    destination: !secret address_work
    region: 'US'
    name: Home to Office

  - platform: time_date
    display_options:
      - 'time'
      - 'date'
        
#  - platform: template
#    sensors:
#        #----------------------------------------------------
#        # Bedroom occupancy status
#        # Used to change lights in room depending on the
#        # the status of Scott.
#        #----------------------------------------------------
#        bedroom_status:
#            friendly_name: 'Bedroom Status'
#            value_template: >-
#                    {%- if is_state('switch.phone_charging_switch', 'on') -%}
#                    Sleeping
#                    {%- elif now().hour >= 7 
#                        and now().hour <= 8
#                        and now().weekday() <= 3 -%}
#                    Traffic
#                    {%- elif states.sun.sun.attributes.elevation | float < 8 %}
#                    Illuminate
#                    {%- elif states.sun.sun.attributes.elevation | float > 8 
#                        and 'Mostly cloudy' in states('weather.my_ecobee3')  -%}
#                    Illuminate
#                    {%- else -%}
#                    off
#                    {%- endif %}
#        office_status:
#            friendly_name: 'Office Status'
#            value_template: >-
#                    {%- if is_state('switch.gaming_computer', 'on') -%}
#                    Gaming
#                    {%- elif states.sun.sun.attributes.elevation | float < 8 %}
#                    Illuminate
#                    {%- elif states.sun.sun.attributes.elevation | float > 8 
#                        and 'Mostly cloudy' in states('weather.my_ecobee3')  -%}
#                    Illuminate
#                    {%- else -%}
#                    off
#                    {%- endif %} 
#        kitchen_status:
#            friendly_name: "Kitchen Status"
#            value_template: >-
#                {%- if is_state('input_boolean.guest', 'On') -%}
#                Guest
#                {%- elif now().hour <= 6 -%}
#                Illuminate Night
#                {%- elif now().hour >= 21 -%}
#                Illuminate Night
#                {%- elif states.sun.sun.attributes.elevation | float < 8 -%}
#                Illuminate Main
#                {%- elif states.sun.sun.attributes.elevation | float > 8 
#                    and 'Mostly cloudy' in states('weather.my_ecobee3')  -%}
#                Illuminate Main
#                {%- else -%}
#                off
#                {%- endif %}
#        living_status:
#            friendly_name: "Living Status"
#            value_template: >-
#                {%-if is_state('input_boolean.movie', 'on') -%}
#                Movie
#                {%- elif is_state_attr('media_player.living_room_tv', 'source', 'Game Console') -%}
#                Switch
#                {%- elif not is_state('media_player.living_room_tv', 'off') -%}
#                TV
#                {%- elif is_state('input_boolean.guest', 'on') -%}
#                Guest
#                {%- elif is_state('sensor.lights_status', 'Illuminate') -%}
#                Illuminate
#                {%- else -%}
#                off
#                {%- endif %} 
#        lights_status:
#            friendly_name:  "Light Status"
#            value_template: >-
#                {%- if states.sun.sun.attributes.elevation | float < 8 -%}
#                Illuminate
#                {%- elif is_state('input_boolean.dark', 'on') -%}
#                Illuminate
#                {%- elif now().hour <= 8 -%}
#                Illuminate
#                {%- elif now().hour >= 19 -%}
#                Illuminate
#                {%- else -%}
#                off
#                {%- endif -%}

        #house_status: #remove
        #    friendly_name: "House Status"
        #    value_template: >- 
        #        {{ not is_state('media_player.living_room_tv', 'off') }}
                
        #outside_temperature:
        #    friendly_name: Temperature
        #    unit_of_measurement: '째F'
        #    value_template: >-
        #        {{ states.weather.my_ecobee3.attributes.temperature }}
                


  - platform: mqtt
    unique_id: "ho"
    name: "ho"
    state_topic: window/office/humidity
    unit_of_measurement: '%'
  - platform: mqtt
    unique_id: "to2"
    name: "to2"
    state_topic: window/office/fahrenheit
    unit_of_measurement: '째F'
  - platform: mqtt
    unique_id: "lo"
    name: "lo"
    state_topic: window/office/light

  - platform: mqtt
    unique_id: "hb"
    name: "hb"
    state_topic: window/bedroom/humidity
    unit_of_measurement: '%'
  - platform: mqtt
    unique_id: "tb"
    name: "tb"
    state_topic: window/bedroom/fahrenheit
    unit_of_measurement: '째F'
  - platform: mqtt
    unique_id: "lb"
    name: "lb"
    state_topic: window/bedroom/light

  - platform: mqtt
    unique_id: "ot"
    name: "ot"
    state_topic: "bridge/t/office/state"
    unit_of_measurement: '째F'